name: Gatling CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gatling-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Add sample image for upload
        run: |
          mkdir -p gatling/**/user-files/resources/images
          echo "dummy" > gatling/**/user-files/resources/images/sample.jpg

      - name: Run Gatling Simulation
        run: |
          cd gatling/gatling-charts-highcharts-bundle-3.9.5/bin
          ./gatling.sh -s simulations.PetstoreCRUDSimulation -nr -rf ${{ github.workspace }}/results

      - name: Publish HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: results/
