name: Gatling CI

on:
  push:
    branches:
      - main

jobs:
  gatling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gatling
        uses: actions/cache@v4
        with:
          path: gatling/gatling-charts-highcharts-bundle-3.9.5
          key: gatling-3.9.5

      - name: Download and setup Gatling
        run: |
          mkdir -p gatling
          curl -L https://repo1.maven.org/maven2/io/gatling/highcharts/gatling-charts-highcharts-bundle/3.9.5/gatling-charts-highcharts-bundle-3.9.5-bundle.zip -o gatling.zip
          unzip gatling.zip -d gatling
          rm gatling.zip

      - name: Prepare simulation resources
        run: |
          mkdir -p gatling/gatling-charts-highcharts-bundle-3.9.5/user-files/resources/images
          echo "dummy" > gatling/gatling-charts-highcharts-bundle-3.9.5/user-files/resources/images/sample.jpg

      - name: Run Gatling Petstore CRUD Simulation
        run: |
          cd gatling/gatling-charts-highcharts-bundle-3.9.5/bin
          ./gatling.sh -s simulations.PetstoreCRUDSimulation -nr -rf results

      - name: Publish Gatling HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: gatling-report
          path: gatling/gatling-charts-highcharts-bundle-3.9.5/bin/results/
